// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct LinkedList
{
  struct LinkedList_vtable *vptr;
};
struct Element
{
  struct Element_vtable *vptr;
  int Age;
  int Salary;
  int Married;
};
struct List
{
  struct List_vtable *vptr;
  int elem;
  int next;
  int end;
};
struct LL
{
  struct LL_vtable *vptr;
};
// vtables structures
struct LinkedList_vtable
{
};

struct Element_vtable
{
  int (*Init)();
  int (*GetAge)();
  int (*GetSalary)();
  int (*GetMarried)();
  int (*Equal)();
  int (*Compare)();
};

struct List_vtable
{
  int (*Init)();
  int (*InitNew)();
  int (*Insert)();
  int (*SetNext)();
  int (*Delete)();
  int (*Search)();
  int (*GetEnd)();
  int (*GetElem)();
  int (*GetNext)();
  int (*Print)();
};

struct LL_vtable
{
  int (*Start)();
};


// methods
int Element_Init(struct Element * this, int v_Age, int v_Salary, int v_Married)
{

  Age = v_Age;  Salary = v_Salary;  Married = v_Married;  return v_Married;
}
int Element_GetAge(struct Element * this)
{

  return Age;
}
int Element_GetSalary(struct Element * this)
{

  return Salary;
}
int Element_GetMarried(struct Element * this)
{

  return Married;
}
int Element_Equal(struct Element * this, int other)
{
  int ret_val;
  int aux01;
  int aux02;
  int nt;
  struct Element * x_1;

  ret_val = Married;  aux01 = (x_1=other, x_1->vptr->GetAge(x_1));  if ((x_1=other, x_1->vptr->GetAge(x_1)))
    ret_val = (x_1=other, x_1->vptr->GetAge(x_1));
  else
    ret_val = (x_1=other, x_1->vptr->GetAge(x_1));
  return ret_val;
}
int Element_Compare(struct Element * this, int num1, int num2)
{
  int retval;
  int aux02;

  retval = ret_val;  aux02 = ret_val;  if (num1 < num2)
    retval = num1 < num2;
  else
    if (num1 < num2)
      retval = num1 < num2;
    else
      retval = num1 < num2;

  return retval;
}
int List_Init(struct List * this)
{

  end = retval;  return retval;
}
int List_InitNew(struct List * this, int v_elem, int v_next, int v_end)
{

  end = v_end;  elem = v_elem;  next = v_next;  return v_next;
}
int List_Insert(struct List * this, int new_elem)
{
  int ret_val;
  int aux03;
  int aux02;
  struct List * x_2;

  aux03 = this;  aux02 = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));  ret_val = (x_2=aux02, x_2->vptr->InitNew(x_2, new_elem, aux03, aux03));  return aux02;
}
int List_SetNext(struct List * this, int v_next)
{

  next = v_next;  return v_next;
}
int List_Delete(struct List * this, int e)
{
  int my_head;
  int ret_val;
  int aux05;
  int aux01;
  int prev;
  int var_end;
  int var_elem;
  int aux04;
  int nt;

  my_head = this;  ret_val = this;  aux04 = this;  aux01 = this;  prev = this;  var_end = end;  var_elem = elem;  var_elem = elem;  return my_head;
}
int List_Search(struct List * this, int e)
{
  int int_ret_val;
  int aux01;
  int var_elem;
  int var_end;
  int nt;

  int_ret_val = 0;  aux01 = this;  var_end = end;  var_elem = elem;  var_elem = elem;  return int_ret_val;
}
int List_GetEnd(struct List * this)
{

  return end;
}
int List_GetElem(struct List * this)
{

  return elem;
}
int List_GetNext(struct List * this)
{

  return next;
}
int List_Print(struct List * this)
{
  int aux01;
  int var_end;
  int var_elem;

  aux01 = this;  var_end = end;  var_elem = elem;  var_elem = elem;  return elem;
}
int LL_Start(struct LL * this)
{
  int head;
  int last_elem;
  int aux01;
  int el01;
  int el02;
  int el03;
  struct List * x_3;
  struct List * x_4;
  struct List * x_5;
  struct Element * x_6;
  struct List * x_7;
  struct List * x_8;
  struct Element * x_9;
  struct List * x_10;
  struct List * x_11;
  struct Element * x_12;
  struct List * x_13;
  struct List * x_14;
  struct Element * x_15;
  struct List * x_16;
  struct List * x_17;
  struct Element * x_18;
  struct List * x_19;
  struct List * x_20;
  struct List * x_21;
  struct List * x_22;
  struct List * x_23;
  struct List * x_24;

  last_elem = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));  aux01 = (x_3=last_elem, x_3->vptr->Init(x_3));  head = last_elem;  aux01 = (x_4=head, x_4->vptr->Init(x_4));  aux01 = (x_5=head, x_5->vptr->Print(x_5));  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));  aux01 = (x_6=el01, x_6->vptr->Init(x_6, 25, 37000, 37000));  head = (x_7=head, x_7->vptr->Insert(x_7, el01));  aux01 = (x_8=head, x_8->vptr->Print(x_8));  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));  aux01 = (x_9=el01, x_9->vptr->Init(x_9, 39, 42000, 42000));  el02 = el01;  head = (x_10=head, x_10->vptr->Insert(x_10, el01));  aux01 = (x_11=head, x_11->vptr->Print(x_11));  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));  aux01 = (x_12=el01, x_12->vptr->Init(x_12, 22, 34000, 34000));  head = (x_13=head, x_13->vptr->Insert(x_13, el01));  aux01 = (x_14=head, x_14->vptr->Print(x_14));  el03 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));  aux01 = (x_15=el03, x_15->vptr->Init(x_15, 27, 34000, 34000));  System_out_println ((x_16=head, x_16->vptr->Search(x_16, el02)));
  System_out_println ((x_17=head, x_17->vptr->Search(x_17, el03)));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));  aux01 = (x_18=el01, x_18->vptr->Init(x_18, 28, 35000, 35000));  head = (x_19=head, x_19->vptr->Insert(x_19, el01));  aux01 = (x_20=head, x_20->vptr->Print(x_20));  System_out_println (2220000);
  head = (x_21=head, x_21->vptr->Delete(x_21, el02));  aux01 = (x_22=head, x_22->vptr->Print(x_22));  System_out_println (33300000);
  head = (x_23=head, x_23->vptr->Delete(x_23, el01));  aux01 = (x_24=head, x_24->vptr->Print(x_24));  System_out_println (44440000);
  return 0;
}

// vtables
struct LinkedList_vtable LinkedList_vtable_ = 
{
};

struct Element_vtable Element_vtable_ = 
{
  Element_Init,
  Element_GetAge,
  Element_GetSalary,
  Element_GetMarried,
  Element_Equal,
  Element_Compare,
};

struct List_vtable List_vtable_ = 
{
  List_Init,
  List_InitNew,
  List_Insert,
  List_SetNext,
  List_Delete,
  List_Search,
  List_GetEnd,
  List_GetElem,
  List_GetNext,
  List_Print,
};

struct LL_vtable LL_vtable_ = 
{
  LL_Start,
};


// main method
int Tiger_main ()
{
  struct LL * x_0;
  System_out_println ((x_0=((struct LL*)(Tiger_new (&LL_vtable_, sizeof(struct LL)))), x_0->vptr->Start(x_0)));
}




